/* B2B Hacks — meme templates (imgflip CDN, hotlinkable) + per-category top-text setups.
   Each question deterministically maps to one template (hash of id) with a
   question-related caption: TOP = setup, BOTTOM = that question's punchline. */
const MEME_TEMPLATES = [
  { name: "Drake Hotline Bling", url: "https://i.imgflip.com/30b1gx.jpg" },
  { name: "Two Buttons", url: "https://i.imgflip.com/1g8my4.jpg" },
  { name: "Distracted Boyfriend", url: "https://i.imgflip.com/1ur9b0.jpg" },
  { name: "UNO Draw 25", url: "https://i.imgflip.com/3lmzyx.jpg" },
  { name: "Left Exit Ramp", url: "https://i.imgflip.com/22bdq6.jpg" },
  { name: "Always Has Been", url: "https://i.imgflip.com/46e43q.png" },
  { name: "Epic Handshake", url: "https://i.imgflip.com/28j0te.jpg" },
  { name: "Gru's Plan", url: "https://i.imgflip.com/26jxvz.jpg" },
  { name: "Waiting Skeleton", url: "https://i.imgflip.com/2fm6x.jpg" },
  { name: "Change My Mind", url: "https://i.imgflip.com/24y43o.jpg" },
  { name: "Trade Offer", url: "https://i.imgflip.com/54hjww.jpg" },
  { name: "X Everywhere", url: "https://i.imgflip.com/1ihzfe.jpg" },
  { name: "Woman Yelling At Cat", url: "https://i.imgflip.com/345v97.jpg" },
  { name: "Mocking Spongebob", url: "https://i.imgflip.com/1otk96.jpg" },
  { name: "One Does Not Simply", url: "https://i.imgflip.com/1bij.jpg" },
  { name: "They're The Same Picture", url: "https://i.imgflip.com/2za3u1.jpg" },
  { name: "Is This A Pigeon", url: "https://i.imgflip.com/1o00in.jpg" },
  { name: "Expanding Brain", url: "https://i.imgflip.com/1jwhww.jpg" },
  { name: "Buff Doge vs Cheems", url: "https://i.imgflip.com/43a45p.png" },
  { name: "Tuxedo Pooh", url: "https://i.imgflip.com/2ybua0.png" },
  { name: "This Is Fine", url: "https://i.imgflip.com/wxica.jpg" },
  { name: "Bernie Asking Again", url: "https://i.imgflip.com/3oevdk.jpg" },
  { name: "Think About Other Women", url: "https://i.imgflip.com/1tl71a.jpg" },
  { name: "Monkey Puppet", url: "https://i.imgflip.com/2gnnjh.jpg" },
  { name: "Clown Makeup", url: "https://i.imgflip.com/38el31.jpg" },
  { name: "Roll Safe", url: "https://i.imgflip.com/1h7in3.jpg" },
  { name: "Spider-Man Triple", url: "https://i.imgflip.com/3eqjd8.jpg" },
  { name: "Imagination Spongebob", url: "https://i.imgflip.com/3i7p.jpg" },
  { name: "They Don't Know", url: "https://i.imgflip.com/4pn1an.png" },
  { name: "Boardroom Suggestion", url: "https://i.imgflip.com/m78d.jpg" },
  { name: "Hide The Pain Harold", url: "https://i.imgflip.com/gk5el.jpg" },
  { name: "All My Homies Hate", url: "https://i.imgflip.com/3kwur5.jpg" },
  { name: "Scientist Myself", url: "https://i.imgflip.com/27qxmb.jpg" },
  { name: "Marked Safe", url: "https://i.imgflip.com/2odckz.jpg" },
  { name: "Bike Fall", url: "https://i.imgflip.com/1b42wl.jpg" },
  { name: "Running Away Balloon", url: "https://i.imgflip.com/261o3j.jpg" },
  { name: "Y'all Got Any More", url: "https://i.imgflip.com/21uy0f.jpg" },
  { name: "Ancient Aliens", url: "https://i.imgflip.com/26am.jpg" },
  { name: "Oprah You Get A", url: "https://i.imgflip.com/gtj5t.jpg" },
  { name: "Squidward Window", url: "https://i.imgflip.com/145qvv.jpg" },
  { name: "Megamind Peeking", url: "https://i.imgflip.com/64sz4u.png" },
  { name: "Pawn Stars", url: "https://i.imgflip.com/19vcz0.jpg" },
  { name: "Bell Curve", url: "https://i.imgflip.com/8tw3vb.png" },
  { name: "Where Monkey", url: "https://i.imgflip.com/58eyvu.png" },
  { name: "Friendship Ended", url: "https://i.imgflip.com/29v4rt.jpg" },
  { name: "Anakin Padme 4 Panel", url: "https://i.imgflip.com/5c7lwq.png" },
  { name: "Bernie Sanders Once Again Asking", url: "https://i.imgflip.com/3pdf2w.png" },
  { name: "Absolute Cinema", url: "https://i.imgflip.com/8d317n.png" },
  { name: "You Guys are Getting Paid", url: "https://i.imgflip.com/2xscjb.png" },
  { name: "0 Days Without (Simpsons)", url: "https://i.imgflip.com/72epa9.png" },
  { name: "Trophy If I Had One", url: "https://i.imgflip.com/1wz1x.jpg" },
  { name: "Soldier Protecting Child", url: "https://i.imgflip.com/2tzo2k.jpg" },
  { name: "Two Guys On A Bus", url: "https://i.imgflip.com/5v6gwj.jpg" },
  { name: "Types Of Headaches", url: "https://i.imgflip.com/1yz6z4.jpg" },
  { name: "Flex Tape", url: "https://i.imgflip.com/2reqtg.png" },
  { name: "Inhaling Seagull", url: "https://i.imgflip.com/1w7ygt.jpg" },
  { name: "Sleeping Shaq", url: "https://i.imgflip.com/1nck6k.jpg" },
  { name: "Anime Girl Vs Terminator", url: "https://i.imgflip.com/3po4m7.jpg" },
  { name: "Scooby Mask Reveal", url: "https://i.imgflip.com/2eeunw.jpg" },
  { name: "Evil Kermit", url: "https://i.imgflip.com/1e7ql7.jpg" },
  { name: "AJ Styles Undertaker", url: "https://i.imgflip.com/3vfrmx.jpg" },
  { name: "Grandma Finds The Internet", url: "https://i.imgflip.com/1bhw.jpg" },
  { name: "Three-Headed Dragon", url: "https://i.imgflip.com/33e92f.jpg" },
  { name: "Panik Kalm Panik", url: "https://i.imgflip.com/3qqcim.png" },
  { name: "Grant Gustin Grave", url: "https://i.imgflip.com/3nx72a.png" },
  { name: "No Yes", url: "https://i.imgflip.com/24zoa8.jpg" },
  { name: "Spiderman Pointing", url: "https://i.imgflip.com/1tkjq9.jpg" },
  { name: "Blank Nut Button", url: "https://i.imgflip.com/1yxkcp.jpg" },
  { name: "Laughing Leo", url: "https://i.imgflip.com/4acd7j.png" },
  { name: "Whisper And Goosebumps", url: "https://i.imgflip.com/1op9wy.jpg" },
  { name: "Domino Effect", url: "https://i.imgflip.com/2oo7h0.jpg" },
  { name: "Surprised Pikachu", url: "https://i.imgflip.com/2kbn1e.jpg" },
  { name: "Is This Butterfly", url: "https://i.imgflip.com/2cjr7j.jpg" },
  { name: "Star Wars Yoda", url: "https://i.imgflip.com/8k0sa.jpg" },
  { name: "Futurama Fry", url: "https://i.imgflip.com/1bgw.jpg" },
  { name: "Third World Skeptical Kid", url: "https://i.imgflip.com/265k.jpg" },
  { name: "Two Paths", url: "https://i.imgflip.com/54d9lj.png" },
  { name: "Who Killed Hannibal", url: "https://i.imgflip.com/28s2gu.jpg" },
  { name: "Say The Line Bart", url: "https://i.imgflip.com/176h0h.jpg" },
  { name: "American Chopper Argument", url: "https://i.imgflip.com/2896ro.jpg" },
  { name: "Charlie Conspiracy", url: "https://i.imgflip.com/1itoun.jpg" },
  { name: "I Am The Captain Now", url: "https://i.imgflip.com/hlmst.jpg" },
  { name: "Drake Blank", url: "https://i.imgflip.com/1iruch.jpg" },
  { name: "Bad Luck Brian", url: "https://i.imgflip.com/1bip.jpg" },
  { name: "Look At Me", url: "https://i.imgflip.com/hmt3v.jpg" },
  { name: "Yo Dawg Heard You", url: "https://i.imgflip.com/26hg.jpg" },
  { name: "Leonardo Cheers", url: "https://i.imgflip.com/39t1o.jpg" },
  { name: "The Scroll Of Truth", url: "https://i.imgflip.com/21tqf4.jpg" },
  { name: "Competition Opponent", url: "https://i.imgflip.com/5youx3.jpg" },
  { name: "Cmon Do Something", url: "https://i.imgflip.com/bwu6w.jpg" },
  { name: "Wolverine Remember", url: "https://i.imgflip.com/s2zxn.jpg" }
];

const MEME_TOPS = {
  "General AI": ["POV: THE MODEL", "ME EXPLAINING AI", "THE ALGORITHM", "TRAINING BE LIKE"],
  "AWS": ["POV: THE CLOUD BILL", "DEPLOYING ON FRIDAY", "AWS BE LIKE", "ME VS THE CONSOLE"],
  "Gen AI": ["POV: THE CHATBOT", "PROMPTING BE LIKE", "THE LLM", "AI SAID WHAT"],
  "Agentic AI": ["POV: THE AGENT", "THE ROBOT INTERN", "AGENTS BE LIKE", "AUTOPILOT ENGAGED"]
};

// deterministic template + setup per question id (stable across reloads)
function memeFor(q) {
  let h = 0; const s = q.id + q.category;
  for (let i = 0; i < s.length; i++) h = ((h * 31) + s.charCodeAt(i)) >>> 0;
  const tops = MEME_TOPS[q.category] || MEME_TOPS["General AI"];
  return { tpl: MEME_TEMPLATES[h % MEME_TEMPLATES.length], top: tops[h % tops.length] };
}
